DEBUG = True
RUN_ON_PI = False

# BOARD CONSTANTS
SQUARE_SIZE = 60
BOARD_SIZE = SQUARE_SIZE * 8

# IMAGE PROCESS
RESCALE_RATIO = 1.015

CANNY_LOWER = 0
CANNY_UPPER = 20
CANNY_BLUR = 11
CANNY_GAMMA = 2

CLAHE_LIMIT = 2.0
CLAHE_GRID = 8

EDGE_DILATE = 5
EDGE_ERODE = 5

MASK_DRAW = True
MASK_BLUR = 9
MASK_DILATE = 9
MASK_DILATE_ITER = 2
MASK_ERODE_ITER = 3
MASK_COLOR = (0,0,0)

THRESHOLD_PRESENCE = 200
THRESHOLD_COLOR = 100
THRESHOLD_BINARY = 100
