DEBUG = True
RUN_ON_PI = False

# BOARD CONSTANTS
SQUARE_SIZE = 60
BOARD_SIZE = SQUARE_SIZE * 8

# IMAGE PROCESS
RESCALE_RATIO = 1.015

CANNY_SIGMA = 0.8
CANNY_LOWER = 80
CANNY_UPPER = 100
CANNY_BLUR = 13
CANNY_GAMMA = 1

CLAHE_LIMIT = 1.0
CLAHE_GRID = 8

EDGE_DILATE = 5
EDGE_ERODE = 5

MASK_DRAW = False
MASK_BLUR = 9
MASK_DILATE = 9
MASK_DILATE_ITER = 3
MASK_ERODE_ITER = 4
MASK_COLOR = (0,0,0)

THRESHOLD_PRESENCE = 150
THRESHOLD_COLOR = 100
THRESHOLD_BINARY = 120
